// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProvider(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddProvider'](arg1, arg2, arg3);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function GetActiveProviderIndex() {
  return window['go']['main']['App']['GetActiveProviderIndex']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function InstallCertificate() {
  return window['go']['main']['App']['InstallCertificate']();
}

export function IsCertificateInstalled() {
  return window['go']['main']['App']['IsCertificateInstalled']();
}

export function IsHostsSet() {
  return window['go']['main']['App']['IsHostsSet']();
}

export function IsProxyRunning() {
  return window['go']['main']['App']['IsProxyRunning']();
}

export function IsRunningAsAdmin() {
  return window['go']['main']['App']['IsRunningAsAdmin']();
}

export function QuickStart() {
  return window['go']['main']['App']['QuickStart']();
}

export function QuickStop() {
  return window['go']['main']['App']['QuickStop']();
}

export function RestoreHosts() {
  return window['go']['main']['App']['RestoreHosts']();
}

export function SetActiveProvider(arg1) {
  return window['go']['main']['App']['SetActiveProvider'](arg1);
}

export function SetHosts() {
  return window['go']['main']['App']['SetHosts']();
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function UninstallCertificate() {
  return window['go']['main']['App']['UninstallCertificate']();
}

export function UpdateProvider(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateProvider'](arg1, arg2, arg3, arg4);
}
