// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProvider(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function DeleteProvider(arg1:number):Promise<void>;

export function GetActiveProviderIndex():Promise<number>;

export function GetProviders():Promise<Array<Record<string, any>>>;

export function GetStatus():Promise<Record<string, any>>;

export function InstallCertificate():Promise<void>;

export function IsCertificateInstalled():Promise<boolean>;

export function IsHostsSet():Promise<boolean>;

export function IsProxyRunning():Promise<boolean>;

export function IsRunningAsAdmin():Promise<boolean>;

export function QuickStart():Promise<void>;

export function QuickStop():Promise<void>;

export function RestoreHosts():Promise<void>;

export function SetActiveProvider(arg1:number):Promise<void>;

export function SetHosts():Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function UninstallCertificate():Promise<void>;

export function UpdateProvider(arg1:number,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;
